### ISSUE TITLE
Not showing package names and getting error 0x800f0805 when trying to remove one

### ISSUE THREAD

**Issue by Stoutscientist** [01101010110/MODWIN#1]
When you go to _Apps, Packages, and Features Options_ and click any of them, the names of them won't show and pop up with an error which can easily be fixed by replacing the `find` commands with `findstr`, but I still get error `0x800f0805` when I paste one of the package names to be removed

**Comment by 01101010110** [comment]
Hello the project has been re-written in C++ and should now function as intended.
