### ISSUE TITLE
Doesn't work on Win11_23H2_French_x64 ISO or Win 11 Dev FR ISO

### ISSUE THREAD

**Issue by machinbidule62** [01101010110/MODWIN#4]
I can't remove or disable

3. WIM's Application Package Menu
4. WIM's Package Menu
5. WIM's Feature Menu

Nothing appears.

Thanks a lot for your excellent tool.

**Comment by MungbeanOuO** [comment]
I looked at the source code and the records of `apps.txt` and `C:\Windows\Logs\DISM\dism.log` to compare and reverse trace.
It is found that if you follow `readme.md`, mounting will not occur when executing step 6. You may need to wait for the author to adjust `modwin.cpp` or `readme.md`.
The temporary solution is to select 2 in the main menu options to mount manually before executing step 6.
In this way, the conditions `C:\MODWIN\PATH` required for `WIM's Application Package Menu`, `WIM's Package Menu`, and `WIM's Feature Menu` can be satisfied.
The tested iso is `Windows11_InsiderPreview_Client_x64_en-us_26016`.
This reply was translated using Google Translate.
![螢幕擷取畫面 2024-01-01 141150](https://github.com/01101010110/MODWIN/assets/42833513/edf0dbed-2fa1-45de-b903-ba7f94b85f4d)

**Comment by 01101010110** [comment]
Hello, MODWIN v6 is out now and I was able to confirm that the french windows iso is working as well as many other languages. The isos all seem to carry the same apps, packages, and features as the english version and spelled out in english when using DISM or MODWIN. The latest release will now give us unattend support, with which the french and any other iso outside of english will require the user to select "start" to install, then the unattend will take over. Thank you for your comment, I hope you are able to get it running now!
